Update AUTHENTICATION.md
osisoft/OSI-Samples-ADH pull request #218
Opened 2022-02-28 21:21 UTC by cbardini

2022-02-28 21:43 UTC, kelseyduffy approved these changes

2022-03-01 08:32 UTC, anton-dahlin approved these changes

2022-03-01 13:15 UTC, derekendres requested changes
outside readme has broken link too for hybrid

2022-03-10 17:51 UTC, derekendres approved these changes

2022-03-10 17:51 UTC, merged