Use collapsible categories and remove pipeline links to ADO
osisoft/OSI-Samples-ADH pull request #230
Opened 2022-07-12 12:44 UTC by anton-dahlin

![image](https://user-images.githubusercontent.com/92155840/178492184-28fcd77f-906a-4693-88e3-e3e54d22e985.png)

## Due to GitHub markdown wrapping links/imgs in an a element they will be clickable, but will only open a tab with the pipeline badge image. There could be ways around this that would require some nifty tricks, but this is the way that others have implemented it, for example axios: https://www.npmjs.com/package/axios - clicking their CI takes you here https://github.com/axios/axios/actions/workflows/ci.yml/badge.svg.

2022-07-12 17:51 UTC, jgaughan-aveva approved these changes

2022-07-15 11:42 UTC, anton-dahlin commented
Removed pipeline badges from category pages based on discussion in daily sync

2022-07-15 14:14 UTC, cbardini requested changes

2022-07-15 14:14 UTC, cbardini commented on README.md
>  ~~ These libraries are tested by being used in other apps.
I think that this line could be removed now that we have the status badges for the library

2022-07-18 14:52 UTC, cbardini approved these changes

2022-07-19 08:20 UTC, merged